name: Deploy to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}
      - name: Build Docker image
        run: docker build -t chat-backend:latest .
      - name: Save Docker image to tar
        run: docker save chat-backend:latest -o chat-backend.tar
      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          source: "chat-backend.tar"
          target: "/root"
          host:  ${{ secrets.VPS_HOST }}
          username: root
          key:  ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          echo "SERVER_HOST=${{ env.SERVER_HOST }}" >> .env
          echo "SERVER_PORT=${{ env.SERVER_PORT }}" >> .env

      - name: Load Docker image on VPS and run
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            docker load -i /root/chat-backend.tar
            docker stop chat-backend || true
            docker rm chat-backend || true
            docker run -d --name chat-backend --env-file .env -p 80:{{ env.SERVER_PORT }} chat-backend:latest
          EOF